name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin pytest
    - name: Build and install
      run: maturin develop
    - name: Run tests
      run: |
        cargo test
        pytest python/tests
